// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial2_ap1_2017_0826.DAL;

namespace Parcial2_ap1_2017_0826.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20210309001037_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Parcial2_ap1_2017_0826.Entidades.Proyectos", b =>
                {
                    b.Property<int>("ProyectoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.HasKey("ProyectoId");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("Parcial2_ap1_2017_0826.Entidades.ProyectosDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Minutos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoTareaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.ToTable("ProyectosDetalle");
                });

            modelBuilder.Entity("Parcial2_ap1_2017_0826.Entidades.TiposTarea", b =>
                {
                    b.Property<int>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("TareaId");

                    b.ToTable("TiposTarea");

                    b.HasData(
                        new
                        {
                            TareaId = 1,
                            Nombre = "Analisis"
                        },
                        new
                        {
                            TareaId = 2,
                            Nombre = "Diseño"
                        },
                        new
                        {
                            TareaId = 3,
                            Nombre = "Programación"
                        },
                        new
                        {
                            TareaId = 4,
                            Nombre = "Prueba"
                        });
                });

            modelBuilder.Entity("Parcial2_ap1_2017_0826.Entidades.ProyectosDetalle", b =>
                {
                    b.HasOne("Parcial2_ap1_2017_0826.Entidades.Proyectos", null)
                        .WithMany("ProyectoDetalle")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Parcial2_ap1_2017_0826.Entidades.Proyectos", b =>
                {
                    b.Navigation("ProyectoDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
